version: '3.3'

services:

  mysql: #temporary
    image: mysql:5.7.23
    env_file:
      - .develop
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  ngix:
    image: nginx:1.15-alpine
    restart: always
    volumes:
      - static_files:/usr/share/www/html
      - ./nginx.template:/etc/nginx/nginx.conf
      - ./nginx.prod.servers.template:/etc/nginx/conf.d/default.conf
    links:
      - api:api
    depends_on:
      - static
      - api
    labels:
      - 'traefik.martires.port=80'
      - 'traefik.martires.frontend.rule=Host:martires.localhost'
      - 'traefik.phpmyadmin.port=80'
      - 'traefik.phpmyadmin.frontend.rule=Host:phpmyadmin.localhost'

  static:
    build: ./static
    volumes:
      - ./static:/app
      - static_files:/static_files
    environment:
      - APP_ENV=production
      - APP_PATH=/app
    command: /bin/bash -c "./build.sh"
    depends_on:
      - api

  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    environment:
      - APP_SETTINGS_PATH=/usr/src/app/config/settings.py
      - APP_ENV=production
      - APP_PATH=/usr/src/app
    command: /bin/bash -c "./run.sh"

  portainer: #temporary
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.localhost'

  traefik: #temporary
    image: traefik
    command:
      - --accesslogsfile=/data/access.log
      - --web
      - --docker
      - --docker.domain=localhost
      - --logLevel=ERROR
      - --entryPoints=Name:http Address::80 #Redirect.EntryPoint:https
    #      - --entryPoints=Name:https Address::443 TLS:/certs/cert.pem,/certs/key.pem
    #      - --defaultentrypoints=http,https
    ports:
      - '80:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  static_files:
