version: '3.3'
 
services:
  backend-service:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 5000:80

  frontend-service:
    build: ./static
    volumes:
      - ./static:/usr/share/nginx/html
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=martires.joncuna.com
     - APP_ENV=develop
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - backend-service