version: '3.3'

services:

  postgres:
    image: postgres:latest
    env_file:
      - .develop
    volumes:
      - ./db:/var/lib/postgresql/data

  pg:
    restart: always
    image: dockage/phppgadmin:latest
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=postgres
      - PHP_PG_ADMIN_SERVER_PORT=5432
      - PHP_PG_ADMIN_SERVER_DEFAULT_DB=template1
      - PHP_PG_ADMIN_SERVER_PG_DUMP_PATH=/usr/bin/pg_dump
      - PHP_PG_ADMIN_SERVER_PG_DUMPALL_PATH=/usr/bin/pg_dumpall
      - PHP_PG_ADMIN_AUTO_COMPLETE=default on
      - PHP_PG_ADMIN_EXTRA_LOGIN_SECURITY=false
      - PHP_PG_ADMIN_OWNED_ONLY=false
      - PHP_PG_ADMIN_SHOW_COMMENTS=true
      - PHP_PG_ADMIN_SHOW_ADVANCED=true
      - PHP_PG_ADMIN_SHOW_SYSTEM=true
      - PHP_PG_ADMIN_MIN_PASSWORD_LENGTH=1
      - PHP_PG_ADMIN_LEFT_WIDTH=200
      - PHP_PG_ADMIN_THEME=cappuccino
    labels:
      - 'traefik.pg.port=80'
      - 'traefik.pg.frontend.rule=Host:pg.localhost'

  ngix:
    image: nginx:1.15-alpine
    restart: always
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.template:/etc/nginx/nginx.conf
      - ./nginx.servers.template:/etc/nginx/conf.d/default.conf
    links:
      - api:api
    depends_on:
      - static
      - api
    labels:
      - 'traefik.martires.port=80'
      - 'traefik.martires.frontend.rule=Host:martires.localhost'

  static:
    build: ./static
    volumes:
      - ./static:/app
    ports:
      - "3000:3000"
    environment:
     - APP_ENV=development
     - APP_PATH=/app
    command: /bin/bash -c "./build.sh"
    depends_on:
      - api

  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    environment:
      - APP_SETTINGS_PATH=/usr/src/app/config/settings.py
      - APP_ENV=development
      - APP_PATH=/usr/src/app
    command: /bin/bash -c "./run.sh"

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.localhost'

  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.localhost'

  traefik:
    image: traefik
    command:
      - --accesslogsfile=/data/access.log
      - --web
      - --docker
      - --docker.domain=localhost
      - --logLevel=ERROR
      - --entryPoints=Name:http Address::80
    ports:
      - '80:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
