version: '3.3'
 
services:

  mysql:
    image: mysql:5.7.23
    env_file:
      - .developer
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  ngix:
    image: nginx:1.15-alpine
    restart: always
#    ports:
#      - "80:80"
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=martires.joncuna.com
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.template:/etc/nginx/conf.d/default.conf
#    command: /bin/bash -c "envsubst \$$NGINX_PORT < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    links:
      - api:api
    depends_on:
      - static
      - api
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:martires.localhost'

  static:
    build: ./static
    volumes:
      - ./static:/app
    ports:
      - "3000:3000"
    environment:
     - APP_ENV=develop
     - APP_PATH=/app
    command: /bin/bash -c "./build.sh"
    depends_on:
      - api

  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
#    expose:
#      - "5000"
#    ports:
#      - "5000:5000"
    environment:
      - APP_SETTINGS_PATH=/usr/src/app/config/settings.py
      - APP_ENV=develop
      - APP_PATH=/usr/src/app
    command: /bin/bash -c "./run.sh"

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.localhost'

  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.localhost'

  traefik:
    image: traefik
    command:
      - --accesslogsfile=/data/access.log
      - --web
      - --docker
      - --docker.domain=localhost
      - --logLevel=DEBUG
      - --entryPoints=Name:http Address::80 #Redirect.EntryPoint:https
#      - --entryPoints=Name:https Address::443 TLS:/certs/cert.pem,/certs/key.pem
#      - --defaultentrypoints=http,https
    ports:
      - '80:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock