version: '3.3'
 
services:

  ngix:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
      - NGINX_HOST=martires.joncuna.com
    volumes:
      - ./static:/usr/share/nginx/html
      - ./nginx.template:/etc/nginx/conf.d/nginx.template
    command: /bin/bash -c "envsubst \$$NGINX_PORT < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    links:
      - api:api
    depends_on:
      - static
      - api

  static:
    build: ./static
    volumes:
      - ./static:/app
    environment:
     - APP_ENV=develop
     - APP_PATH=/app
    command: /bin/bash -c "./build.sh"
    depends_on:
      - api

  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - APP_SETTINGS_PATH=/usr/src/app/config/settings.py
      - APP_ENV=develop
      - APP_PATH=/usr/src/app
    command: /bin/bash -c "./run.sh"